name: Trigger auto deployment for demomodelcontainerappname

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/demomodelcontainerappname-AutoDeployTrigger-7d34f457-7f66-4297-9e5d-ce8b3c8ba0d8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: azuremlapidemo.azurecr.io
          username: ${{ secrets.DEMOMODELCONTAINERAPPNAME_REGISTRY_USERNAME }}
          password: ${{ secrets.DEMOMODELCONTAINERAPPNAME_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azuremlapidemo.azurecr.io/demo_model:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOMODELCONTAINERAPPNAME_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n demomodelcontainerappname -g AzureContainerApps --server azuremlapidemo.azurecr.io --username  ${{ secrets.DEMOMODELCONTAINERAPPNAME_REGISTRY_USERNAME }} --password ${{ secrets.DEMOMODELCONTAINERAPPNAME_REGISTRY_PASSWORD }}
            az containerapp update -n demomodelcontainerappname -g AzureContainerApps --image azuremlapidemo.azurecr.io/demo_model:${{ github.sha }}
